// Localization for AI Family Books. Danish is the default (the app imports Danish/Swedish .ged
// trees); Swedish, Norwegian, and English are also supported.
//
// This module holds the book-chrome strings (cover, contents, titles) AND the deterministic
// narrative fragments, so that a book is fully localized even when it falls back to the
// deterministic composers (no API key). The AI composers additionally instruct the model to write
// in the chosen language. Keep the templates simple and natural; they take pre-formatted values.

import { BookLanguage } from '../types';

export const BOOK_LANGUAGES: Array<{ value: BookLanguage; label: string; native: string }> = [
  { value: 'da', label: 'Danish', native: 'Dansk' },
  { value: 'sv', label: 'Swedish', native: 'Svenska' },
  { value: 'no', label: 'Norwegian', native: 'Norsk' },
  { value: 'en', label: 'English', native: 'English' },
];

export const DEFAULT_BOOK_LANGUAGE: BookLanguage = 'da';

type EraPart = 'early' | 'mid' | 'late';

const eraPart = (year: number): EraPart => {
  const hundreds = Math.floor(year / 100) * 100;
  const within = year - hundreds;
  return within < 33 ? 'early' : within < 66 ? 'mid' : 'late';
};

const ordinal = (n: number): string => {
  const suffixes = ['th', 'st', 'nd', 'rd'];
  const value = n % 100;
  return n + (suffixes[(value - 20) % 10] || suffixes[value] || suffixes[0]);
};

const eraLabelEn = (year: number): string => {
  const century = Math.floor((year - 1) / 100) + 1;
  const within = (year - 1) % 100;
  const part = within < 33 ? 'early' : within < 66 ? 'mid' : 'late';
  return `${part} ${ordinal(century)} century`;
};

const eraLabelScand = (year: number, partMap: Record<EraPart, string>, suffix: string): string => {
  const hundreds = Math.floor(year / 100) * 100;
  return `${partMap[eraPart(year)]} ${hundreds}-${suffix}`;
};

/** English name of the language, used to instruct the model ("Write entirely in Danish"). */
const LANGUAGE_NAME: Record<BookLanguage, string> = {
  da: 'Danish',
  sv: 'Swedish',
  no: 'Norwegian',
  en: 'English',
};

export interface BookStrings {
  languageName: string;
  // chrome
  familyHistory: (surname: string) => string;
  theFamily: (surname: string) => string;
  narrativeChronicle: (span: string) => string;
  coverLabel: string;
  contents: string;
  lives: (n: number) => string;
  generatedBy: string;
  spanPhrase: (earliest: number | null, latest: number | null) => string;
  eraLabel: (year: number) => string;
  // deterministic person biography fragments
  bio: {
    born: (name: string, year: string | null, place: string, parents: string) => string;
    married: (spouse: string) => string;
    partner: (partner: string) => string;
    raised: (n: number, names: string) => string;
    workedAs: (occupation: string) => string;
    fewRecords: (name: string) => string;
    died: (name: string, year: string, place: string, age: number | null) => string;
    deathUnknown: (name: string) => string;
    legacy: (name: string) => string;
  };
  // deterministic historical context
  hist: {
    spanYears: (years: number, era: string) => string;
    spanEra: (era: string) => string;
    witness: (place: string) => string;
    occupation: (occupation: string) => string;
  };
  // deterministic overview chapter
  overview: {
    family: (surname: string) => string;
    chronicles: (family: string, count: number, span: string, places: string) => string;
    acrossGens: (n: number) => string;
    acrossYears: string;
    witness: (genClause: string, family: string) => string;
    trades: (trades: string) => string;
    following: (treeName: string | null) => string;
  };
}

const en: BookStrings = {
  languageName: 'English',
  familyHistory: (surname) => (surname ? `${surname} Family History` : 'Family History'),
  theFamily: (surname) => (surname ? `The ${surname} Family` : 'Our Family'),
  narrativeChronicle: (span) => `A Narrative Chronicle ${span}`.trim(),
  coverLabel: 'A Linegra Family Chronicle',
  contents: 'Contents',
  lives: (n) => `${n} ${n === 1 ? 'life' : 'lives'}`,
  generatedBy: 'Generated by Linegra',
  spanPhrase: (e, l) => (e != null && l != null ? `${e}–${l}` : e != null ? `from ${e}` : l != null ? `through ${l}` : ''),
  eraLabel: eraLabelEn,
  bio: {
    born: (name, year, place, parents) =>
      `${name} was ${year ? `born in ${year}` : 'whose birth year is not recorded'}${place ? ` in ${place}` : ''}${parents ? `, a child of ${parents}` : ''}.`,
    married: (spouse) => `married ${spouse}`,
    partner: (partner) => `lived as partners with ${partner}`,
    raised: (n, names) => `raised ${n} ${n === 1 ? 'child' : 'children'}${names ? ` (${names})` : ''}`,
    workedAs: (occupation) => `worked as ${occupation}`,
    fewRecords: (name) => `Few records of ${name}'s working and family life have survived in the archive.`,
    died: (name, year, place, age) =>
      `${name} died in ${year}${place ? ` in ${place}` : ''}${age != null ? ` at about ${age} years of age` : ''}.`,
    deathUnknown: (name) => `The circumstances of ${name}'s death are not recorded in the archive.`,
    legacy: (name) =>
      `${name}'s story is preserved here as one thread in the larger tapestry of kinship, place, and time this book traces — a reminder that every name in a family tree was once a lived life.`,
  },
  hist: {
    spanYears: (years, era) => `Living across roughly ${years} years in ${era},`,
    spanEra: (era) => `Living in ${era},`,
    witness: (place) =>
      ` families in ${place} would have witnessed waves of social and technological change — the drift between countryside and growing towns, shifting borders, and the gradual modernization of work, transport, and family life.`,
    occupation: (occupation) =>
      ` As ${/^[aeiou]/i.test(occupation) ? 'an' : 'a'} ${occupation.toLowerCase()}, their days would have followed the rhythms of that work and the seasons it depended on.`,
  },
  overview: {
    family: (surname) => (surname ? `the ${surname} family` : 'this family'),
    chronicles: (family, count, span, places) =>
      `This volume chronicles ${family} — ${count} ${count === 1 ? 'person' : 'people'} ${span}${places}.`,
    acrossGens: (n) => ` Across some ${n} generations,`,
    acrossYears: ' Over the years,',
    witness: (genClause, family) =>
      `${genClause} ${family} would have lived through sweeping change: the rise and fall of trades, the movement between countryside and town, wars and epidemics, and the quieter revolutions of daily and family life.`,
    trades: (trades) => (trades ? ` Common livelihoods included ${trades}.` : ''),
    following: (treeName) =>
      `What follows is a narrative drawn from the records preserved in the archive${treeName ? ` for the ${treeName} tree` : ''}. Each chapter traces a single life, set against the broader currents of the era it was lived in.`,
  },
};

const da: BookStrings = {
  languageName: 'Danish',
  familyHistory: (surname) => (surname ? `${surname}-slægtens historie` : 'Slægtshistorie'),
  theFamily: (surname) => (surname ? `${surname}-slægten` : 'Vores slægt'),
  narrativeChronicle: (span) => `En slægtskrønike ${span}`.trim(),
  coverLabel: 'En Linegra-slægtskrønike',
  contents: 'Indhold',
  lives: (n) => `${n} liv`,
  generatedBy: 'Genereret af Linegra',
  spanPhrase: (e, l) => (e != null && l != null ? `${e}–${l}` : e != null ? `fra ${e}` : l != null ? `til ${l}` : ''),
  eraLabel: (year) => eraLabelScand(year, { early: 'begyndelsen af', mid: 'midten af', late: 'slutningen af' }, 'tallet'),
  bio: {
    born: (name, year, place, parents) =>
      `${name} ${year ? `blev født i ${year}` : 'har et ikke-registreret fødselsår'}${place ? ` i ${place}` : ''}${parents ? ` som barn af ${parents}` : ''}.`,
    married: (spouse) => `giftede sig med ${spouse}`,
    partner: (partner) => `levede sammen med ${partner} som ugift par`,
    raised: (n, names) => `fik ${n} ${n === 1 ? 'barn' : 'børn'}${names ? ` (${names})` : ''}`,
    workedAs: (occupation) => `arbejdede som ${occupation}`,
    fewRecords: (name) => `Få optegnelser om ${name}s arbejde og familieliv er bevaret i arkivet.`,
    died: (name, year, place, age) =>
      `${name} døde i ${year}${place ? ` i ${place}` : ''}${age != null ? ` i omkring ${age}-års alderen` : ''}.`,
    deathUnknown: (name) => `Omstændighederne omkring ${name}s død er ikke registreret i arkivet.`,
    legacy: (name) =>
      `${name}s historie bevares her som en tråd i det større væv af slægt, sted og tid, som denne bog beskriver — en påmindelse om, at hvert navn i et stamtræ engang var et levet liv.`,
  },
  hist: {
    spanYears: (years, era) => `Gennemløbende omtrent ${years} år i ${era}, oplevede`,
    spanEra: (era) => `I ${era} oplevede`,
    witness: (place) =>
      ` familier i ${place} bølger af social og teknologisk forandring — flytningen mellem land og voksende byer, skiftende grænser og den gradvise modernisering af arbejde, transport og familieliv.`,
    occupation: (occupation) =>
      ` Som ${occupation.toLowerCase()} fulgte dagene arbejdets rytme og de årstider, det afhang af.`,
  },
  overview: {
    family: (surname) => (surname ? `${surname}-slægten` : 'denne slægt'),
    chronicles: (family, count, span, places) =>
      `Denne bog skildrer ${family} — ${count} ${count === 1 ? 'person' : 'personer'} ${span}${places}.`,
    acrossGens: (n) => ` Gennem omkring ${n} generationer`,
    acrossYears: ' Gennem årene',
    witness: (genClause, family) =>
      `${genClause} levede ${family} sig gennem stor forandring: håndværks fagenes opkomst og fald, flytningen mellem land og by, krige og epidemier og de stille revolutioner i hverdags- og familielivet.`,
    trades: (trades) => (trades ? ` Almindelige erhverv talte ${trades}.` : ''),
    following: (treeName) =>
      `Det, der følger, er en fortæalling draget af de optegnelser, der er bevaret i arkivet${treeName ? ` for ${treeName}-træet` : ''}. Hvert kapitel følger et enkelt liv, sat op mod de bredere strømninger i den tid, det blev levet i.`,
  },
};

const sv: BookStrings = {
  languageName: 'Swedish',
  familyHistory: (surname) => (surname ? `${surname}-släktens historia` : 'Släktshistoria'),
  theFamily: (surname) => (surname ? `${surname}-släkten` : 'Vår släkt'),
  narrativeChronicle: (span) => `En släktkrönika ${span}`.trim(),
  coverLabel: 'En Linegra-släktkrönika',
  contents: 'Innehåll',
  lives: (n) => `${n} liv`,
  generatedBy: 'Genererad av Linegra',
  spanPhrase: (e, l) => (e != null && l != null ? `${e}–${l}` : e != null ? `från ${e}` : l != null ? `till ${l}` : ''),
  eraLabel: (year) => eraLabelScand(year, { early: 'början av', mid: 'mitten av', late: 'slutet av' }, 'talet'),
  bio: {
    born: (name, year, place, parents) =>
      `${name} ${year ? `föddes ${year}` : 'har inte något registrerat födelseår'}${place ? ` i ${place}` : ''}${parents ? ` som barn till ${parents}` : ''}.`,
    married: (spouse) => `giftede sig med ${spouse}`,
    partner: (partner) => `levde tillsammans med ${partner} som ogift par`,
    raised: (n, names) => `fick ${n} ${n === 1 ? 'barn' : 'barn'}${names ? ` (${names})` : ''}`,
    workedAs: (occupation) => `arbetade som ${occupation}`,
    fewRecords: (name) => `Få uppgifter om ${name}s arbete och familjeliv bevarades i arkivet.`,
    died: (name, year, place, age) =>
      `${name} dog ${year}${place ? ` i ${place}` : ''}${age != null ? ` vid omkring ${age} års ålder` : ''}.`,
    deathUnknown: (name) => `Omständigheterna kring ${name}s död är inte registrerade i arkivet.`,
    legacy: (name) =>
      `${name}s berättelse bevaras här som en tråd i det större väv av släkt, plats och tid som denna bok skildrar — en påminnelse om att varje namn i ett släktträd en gång var ett levt liv.`,
  },
  hist: {
    spanYears: (years, era) => `Under ungefär ${years} år på ${era} upplevde`,
    spanEra: (era) => `På ${era} upplevde`,
    witness: (place) =>
      ` familjer i ${place} vågor av social och teknisk förändring — driften mellan landsbygd och växande städer, skiftande gränser och den gradvisa moderniseringen av arbete, transport och familjeliv.`,
    occupation: (occupation) =>
      ` Som ${occupation.toLowerCase()} präglades dagarna av arbetets rytm och de årstider det berodde av.`,
  },
  overview: {
    family: (surname) => (surname ? `${surname}-släkten` : 'denna släkt'),
    chronicles: (family, count, span, places) =>
      `Denna bok skildrar ${family} — ${count} ${count === 1 ? 'person' : 'personer'} ${span}${places}.`,
    acrossGens: (n) => ` Genom ungefär ${n} generationer`,
    acrossYears: ' Genom åren',
    witness: (genClause, family) =>
      `${genClause} levde ${family} igenom stor förändring: yrkenas uppgång och fall, flytten mellan landsbygd och stad, krig och epidemier och de tysta revolutionerna i vardags- och familjelivet.`,
    trades: (trades) => (trades ? ` Vanliga yrken var bland annat ${trades}.` : ''),
    following: (treeName) =>
      `Det som följer är en berättelse hämtad från de uppgifter som bevarats i arkivet${treeName ? ` för ${treeName}-trädet` : ''}. Varje kapitel följer ett enda liv, satt mot de bredare strömningarna i den tid det leddes i.`,
  },
};

const no: BookStrings = {
  languageName: 'Norwegian',
  familyHistory: (surname) => (surname ? `${surname}-slektens historie` : 'Slektshistorie'),
  theFamily: (surname) => (surname ? `${surname}-slekten` : 'Vår slekt'),
  narrativeChronicle: (span) => `En slektkrønike ${span}`.trim(),
  coverLabel: 'En Linegra-slektkrønike',
  contents: 'Innhold',
  lives: (n) => `${n} liv`,
  generatedBy: 'Generert av Linegra',
  spanPhrase: (e, l) => (e != null && l != null ? `${e}–${l}` : e != null ? `fra ${e}` : l != null ? `til ${l}` : ''),
  eraLabel: (year) => eraLabelScand(year, { early: 'begynnelsen av', mid: 'midten av', late: 'slutningen av' }, 'tallet'),
  bio: {
    born: (name, year, place, parents) =>
      `${name} ${year ? `ble født i ${year}` : 'har ikke registrert fødselsår'}${place ? ` i ${place}` : ''}${parents ? ` som barn av ${parents}` : ''}.`,
    married: (spouse) => `giftet seg med ${spouse}`,
    partner: (partner) => `levde sammen med ${partner} som ugift par`,
    raised: (n, names) => `fikk ${n} ${n === 1 ? 'barn' : 'barn'}${names ? ` (${names})` : ''}`,
    workedAs: (occupation) => `arbeidet som ${occupation}`,
    fewRecords: (name) => `Få oppføringer om ${name}s arbeid og familieliv er bevart i arkivet.`,
    died: (name, year, place, age) =>
      `${name} døde i ${year}${place ? ` i ${place}` : ''}${age != null ? ` i omkring ${age}-års alderen` : ''}.`,
    deathUnknown: (name) => `Omstendighetene rundt ${name}s død er ikke registrert i arkivet.`,
    legacy: (name) =>
      `${name}s historie bevares her som en tråd i det større vevet av slekt, sted og tid som denne boken skildrer — en påminnelse om at hvert navn i et stamtre en gang var et levd liv.`,
  },
  hist: {
    spanYears: (years, era) => `Gjennom omtrent ${years} år i ${era} opplevde`,
    spanEra: (era) => `I ${era} opplevde`,
    witness: (place) =>
      ` familier i ${place} bølger av sosial og teknologisk endring — flyttingen mellom land og voksende byer, skiftende grenser og den gradvise moderniseringen av arbeid, transport og familieliv.`,
    occupation: (occupation) =>
      ` Som ${occupation.toLowerCase()} fulgte dagene arbeidets rytme og de årstidene det avhang av.`,
  },
  overview: {
    family: (surname) => (surname ? `${surname}-slekten` : 'denne slekten'),
    chronicles: (family, count, span, places) =>
      `Denne boken skildrer ${family} — ${count} ${count === 1 ? 'person' : 'personer'} ${span}${places}.`,
    acrossGens: (n) => ` Gjennom omtrent ${n} generasjoner`,
    acrossYears: ' Gjennom årene',
    witness: (genClause, family) =>
      `${genClause} levde ${family} gjennom stor endring: yrkenes framvekst og fall, flyttingen mellom land og by, krig og epidemier og de stille revolusjonene i hverdags- og familielivet.`,
    trades: (trades) => (trades ? ` Vanlige yrker var blant annet ${trades}.` : ''),
    following: (treeName) =>
      `Det som følger, er en fortelling hentet fra de oppføringer som er bevart i arkivet${treeName ? ` for ${treeName}-treet` : ''}. Hvert kapittel følger ett enkelt liv, satt mot de bredere strømningene i den tiden det ble levd i.`,
  },
};

const PACKS: Record<BookLanguage, BookStrings> = { en, da, sv, no };

export const bookStrings = (language: BookLanguage): BookStrings => PACKS[language] ?? PACKS[DEFAULT_BOOK_LANGUAGE];

export const languageName = (language: BookLanguage): string => LANGUAGE_NAME[language] ?? LANGUAGE_NAME[DEFAULT_BOOK_LANGUAGE];
