// Roadmap U7 — markdown alternate representation for public person pages.

import type { PublicCrawlRelationshipGroups } from './publicCrawlRelations';
import type { PublicCrawlSourceRef } from './publicCrawlSources';
import type { PublicFamilyCrawlPayload } from './publicCrawlService';
import { formatPersonDisplayName } from './publicCrawlPrivacy';
import { buildPersonUrl, buildTreeUrl } from './publicRoutes';

export interface PublicPersonMarkdownInput {
  treeId: string;
  treeName: string;
  person: {
    id: string;
    firstName?: string | null;
    lastName?: string | null;
    title?: string | null;
    birthDate?: string | null;
    deathDate?: string | null;
    birthPlace?: string | null;
    deathPlace?: string | null;
    bio?: string | null;
  };
  relationships: PublicCrawlRelationshipGroups;
  sources?: PublicCrawlSourceRef[];
  origin?: string;
}

const linkSection = (
  title: string,
  links: { relationshipLabel: string; name: string; href: string; familyPageHref?: string }[]
) => {
  if (!links.length) return '';
  const lines = links.map((link) => {
    const familySuffix = link.familyPageHref ? ` · [family page](${link.familyPageHref})` : '';
    return `- ${link.relationshipLabel}: [${link.name}](${link.href})${familySuffix}`;
  });
  return `## ${title}\n${lines.join('\n')}\n`;
};

const childUnionSections = (groups: PublicPersonMarkdownInput['relationships']['childUnions']) => {
  if (!groups.length) return '';
  return groups
    .map((group) => {
      const heading = group.familyPageHref
        ? `## [${group.heading}](${group.familyPageHref})`
        : `## ${group.heading}`;
      const lines = group.children.map(
        (link) => `- ${link.relationshipLabel}: [${link.name}](${link.href})`
      );
      return `${heading}\n${lines.join('\n')}`;
    })
    .join('\n\n');
};

const sourcesSection = (sources: PublicCrawlSourceRef[]) => {
  if (!sources.length) return '';
  const lines = sources.map((source) => {
    const link = source.url ? `[${source.title}](${source.url})` : `**${source.title}**`;
    return `- ${link} — ${source.summary}`;
  });
  return `## Sources\n${lines.join('\n')}\n`;
};

export const renderPublicPersonMarkdown = (input: PublicPersonMarkdownInput): string => {
  const name = formatPersonDisplayName(input.person);
  const personUrl = buildPersonUrl(input.treeId, input.person.id, input.origin);
  const treeUrl = buildTreeUrl(input.treeId, input.origin);
  const vitals = [
    input.person.birthDate ? `- Birth: ${input.person.birthDate}${input.person.birthPlace ? ` — ${input.person.birthPlace}` : ''}` : null,
    input.person.deathDate ? `- Death: ${input.person.deathDate}${input.person.deathPlace ? ` — ${input.person.deathPlace}` : ''}` : null,
  ].filter(Boolean);

  return [
    `# ${name}`,
    '',
    `Tree: [${input.treeName}](${treeUrl})`,
    `Canonical URL: ${personUrl}`,
    '',
    vitals.length ? `## Vitals\n${vitals.join('\n')}` : '',
    input.person.bio?.trim() ? `## Biography\n${input.person.bio.trim()}` : '',
    linkSection('Parents', input.relationships.parents),
    linkSection('Spouses & partners', input.relationships.spouses),
    input.relationships.childUnions.length
      ? childUnionSections(input.relationships.childUnions)
      : linkSection('Children', input.relationships.children),
    linkSection('Siblings', input.relationships.siblings),
    sourcesSection(input.sources ?? []),
    '',
    '_Generated by Linegra public crawl API. Living and private persons are omitted from indexes._',
  ]
    .filter(Boolean)
    .join('\n');
};

export const renderPublicFamilyMarkdown = (
  input: Pick<PublicFamilyCrawlPayload, 'treeName' | 'treeId' | 'treeSlug' | 'union' | 'spouses' | 'children'> & {
    origin?: string;
  }
): string => {
  const treeUrl = buildTreeUrl({ id: input.treeId, slug: input.treeSlug }, input.origin);
  const spouseNames = input.spouses.map((spouse) => spouse.name).join(' and ');
  const unionLabel = input.union.type === 'partner' ? 'Partnership' : 'Marriage';
  const unionFacts = [input.union.date, input.union.place].filter(Boolean).join(', ');
  const lines = [
    `# ${spouseNames}`,
    '',
    `Tree: [${input.treeName}](${treeUrl})`,
    `Canonical URL: ${input.union.familyPageHref}`,
    '',
    `## ${unionLabel}`,
    unionFacts ? `- ${unionFacts}` : '',
    '',
    '## Spouses',
    ...input.spouses.map((spouse) => `- [${spouse.name}](${spouse.href})`),
    '',
    '## Children',
    ...input.children.map((child) => `- ${child.relationshipLabel}: [${child.name}](${child.href})`),
    '',
    '_Generated by Linegra public crawl API. Living and private persons are omitted from indexes._',
  ];
  return lines.filter((line) => line !== '').join('\n');
};
