// Roadmap U7 — markdown alternate representation for public person pages.

import type { PublicCrawlRelationshipGroups } from './publicCrawlRelations';
import { formatPersonDisplayName } from './publicCrawlPrivacy';
import { buildPersonUrl, buildTreeUrl } from './publicRoutes';

export interface PublicPersonMarkdownInput {
  treeId: string;
  treeName: string;
  person: {
    id: string;
    firstName?: string | null;
    lastName?: string | null;
    title?: string | null;
    birthDate?: string | null;
    deathDate?: string | null;
    birthPlace?: string | null;
    deathPlace?: string | null;
    bio?: string | null;
  };
  relationships: PublicCrawlRelationshipGroups;
  origin?: string;
}

const linkSection = (title: string, links: { relationshipLabel: string; name: string; href: string }[]) => {
  if (!links.length) return '';
  const lines = links.map((link) => `- ${link.relationshipLabel}: [${link.name}](${link.href})`);
  return `## ${title}\n${lines.join('\n')}\n`;
};

export const renderPublicPersonMarkdown = (input: PublicPersonMarkdownInput): string => {
  const name = formatPersonDisplayName(input.person);
  const personUrl = buildPersonUrl(input.treeId, input.person.id, input.origin);
  const treeUrl = buildTreeUrl(input.treeId, input.origin);
  const vitals = [
    input.person.birthDate ? `- Birth: ${input.person.birthDate}${input.person.birthPlace ? ` — ${input.person.birthPlace}` : ''}` : null,
    input.person.deathDate ? `- Death: ${input.person.deathDate}${input.person.deathPlace ? ` — ${input.person.deathPlace}` : ''}` : null,
  ].filter(Boolean);

  return [
    `# ${name}`,
    '',
    `Tree: [${input.treeName}](${treeUrl})`,
    `Canonical URL: ${personUrl}`,
    '',
    vitals.length ? `## Vitals\n${vitals.join('\n')}` : '',
    input.person.bio?.trim() ? `## Biography\n${input.person.bio.trim()}` : '',
    linkSection('Parents', input.relationships.parents),
    linkSection('Spouses & partners', input.relationships.spouses),
    linkSection('Children', input.relationships.children),
    linkSection('Siblings', input.relationships.siblings),
    '',
    '_Generated by Linegra public crawl API. Living and private persons are omitted from indexes._',
  ]
    .filter(Boolean)
    .join('\n');
};
